### ISSUE TITLE
modapeV1: issue when smoothing (global?) files

### ISSUE THREAD

**Issue by valpesendorfer** [WFP-VAM/modape#106]
![image](https://user-images.githubusercontent.com/18698817/92227281-55d18e00-eea6-11ea-8210-0b688e448eec.png)

**Comment by valpesendorfer** [comment]
there seems to be an issue when smoothing global files (didn't see that in tiled ones)

**Comment by interob** [comment]
This issue is listed as related to smoothing; could it be the export (window)?

BTW: smoothing + export seems to work just fine when working with MODIS VI @1km product

**Comment by valpesendorfer** [comment]
Thanks @interob - looks like the problem is actually within the temporal interpolation. Will add a fix shortly

**Comment by valpesendorfer** [comment]
fixed with #110
