### ISSUE TITLE
Smarter handling of the vam.whittaker dependency when it's already installed

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#108]
https://github.com/WFP-VAM/modape/blob/bc046b20ba33bf8878b9d28c9ad8cdbc157de65c/setup.py#L9-L20

Would be nice add a bit of logic that detects vam.whittaker already installed: in that case simply adding it as a dependency would be enhough -- no need for Cython.

**Comment by valpesendorfer** [comment]
I think we'll keep it separate for now just to make it easy. Going to close the issue, please feel free to continue the discussion if necessary.
