### ISSUE TITLE
Rounding issues when exporting per roi

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#117]
Exporting from 1km MODIS product for the entire African continent by roi = { 26E to 58W, 35S to 38N } @0.01 resolution, a GTiff is produced that has the following geo-referencing (gdalinfo):
`gdalinfo AFRICAvim201001d1.tif`
`Driver: GTiff/GeoTIFF`
`Files: AFRICAvim201001d1.tif`
`Size is 8400, 7300`
`Data axis to CRS axis mapping: 2,1`
`Origin = (-26.002218674392989,37.999999996410878)`
`Pixel Size = (0.010000000000000,-0.010000000000000)`
`Metadata:`
`  AREA_OR_POINT=Area`
`  FINAL=TRUE`
`Image Structure Metadata:`
`  COMPRESSION=LZW`
`  INTERLEAVE=BAND`
`Corner Coordinates:`
`Upper Left  ( -26.0022187,  38.0000000) ( 26d 0' 7.99"W, 38d 0' 0.00"N)`
`Lower Left  ( -26.0022187, -35.0000000) ( 26d 0' 7.99"W, 35d 0' 0.00"S)`
`Upper Right (  57.9977813,  38.0000000) ( 57d59'52.01"E, 38d 0' 0.00"N)`
`Lower Right (  57.9977813, -35.0000000) ( 57d59'52.01"E, 35d 0' 0.00"S)`
`Center      (  15.9977813,   1.5000000) ( 15d59'52.01"E,  1d30' 0.00"N)`
`Band 1 Block=8400x1 Type=Int16, ColorInterp=Gray`
`  NoData Value=-3000`

These rounding issues can be fixed by reapplying the transformation matrix (pixelspace -> world), before line 242
https://github.com/WFP-VAM/modape/blob/5dd5fa7b942b0a6f6a946b353050d50b9abda9b2/modape/modis/window.py#L242

(UPDATE: I created a PR for this one)

**Comment by interob** [comment]
Do I need to update PR #136 ?

**Comment by valpesendorfer** [comment]
> Do I need to update PR #136 ?

Ideally yes, see my comment on the PR

**Comment by valpesendorfer** [comment]
fixed with #136
