### ISSUE TITLE
Have ModisMosaic.generate_mosaics return a list of actually exported mosaics/subsets (filenames)

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#119]
In production, coping with the NRT nature of the time series (time steps receiving updates), it is very helpful to get a list of actually exported mosaics/subsets (filenames) returned by ModisMosaic.generate_mosaics. This list can then be used for follow up actions: e.g. re-computing the MD5 hash that is exposed to clients to detect time step updates sitting in the download location.

**Comment by valpesendorfer** [comment]
addressed by #130
