### ISSUE TITLE
download by native MODIS timestamp (formerly known as "strict date handling")

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#123]
In the 1.0RC a new flag "--strict-dates" has been introduced. The implementation in modape/modis/download.py is different from what I am looking for. I now realise that this difference is the consequence from the misconception / misnaming of the flag.

What I am looking for is to match on native MODIS timestamp (=temporal coverage _start_) only -- rather than the _period_ that a time step covers. This is the only way a _single_ time step can be downloaded -- otherwise, given the Aqua/Terra interleaving/overlap, the download always yields 2 downloads (except for the latest-available-time step; but that's just because no more data is available).

Suggestion:
1. Rename the modis_download flag into "--match-native-datestamp"
2. change the implementation to enforce the result["time_start"] only

**Comment by valpesendorfer** [comment]
I see your point. 

We'll lose the option of enforcing anything on the end of the compositing period, but that was never the goal (and quite honestly I'm not sure if anyone would have a use for that). 

So I think the change is OK. Just the flag naming is a mouthful. How about `--strict-begin`?

**Comment by interob** [comment]
I don't like the "strict" (I know I have come up with it myself, earlier); how about: --by-native-timestamp?

**Comment by interob** [comment]
> I see your point.
> 
> We'll lose the option of enforcing anything on the end of the compositing period, but that was never the goal (and quite honestly I'm not sure if anyone would have a use for that).
> 
> So I think the change is OK. Just the flag naming is a mouthful. How about `--strict-begin`?

How about `--filter-begin`?

**Comment by interob** [comment]
> I see your point.
> 
> We'll lose the option of enforcing anything on the end of the compositing period, but that was never the goal (and quite honestly I'm not sure if anyone would have a use for that).
> 
> So I think the change is OK. Just the flag naming is a mouthful. How about `--strict-begin`?

My second (or 3rd, 4th) thought actually is that `--match-begin` would be best...

**Comment by valpesendorfer** [comment]
I think I can live with `--match-begin` ... not to far from strict (which is still my fav) but let's settle on the match then
