### ISSUE TITLE
modis_download does not return results

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#126]
The 1.0RC has seen a new flag introduced: --return-results. In the implementation, available downloads are printed to console.

This is nice, but not what I was after... Instead, I need the def cli() in modis_download.py to return a list, rather than None.

I propose to rename the --return-results flag to --print-results

**Comment by valpesendorfer** [comment]
The reason is that the `cli` method is originally meant to be used by the cli script ... but I don't see any immediate issue with having it returning the list.

Your suggestion for changing the name if the flag also makes sense.

**Comment by valpesendorfer** [comment]
Please see changes requested in PR #135 

https://github.com/WFP-VAM/modape/pull/135#discussion_r539628588

**Comment by valpesendorfer** [comment]
closed with #135
