### ISSUE TITLE
Corrupted downloads not being detected and modis_collect appending these into the .collected files listing

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#137]
When a download is corrupt, this is not detected (could be detected through the checksum that is in the .xml file that is sitting next to the .hdf)

When modis_collect finds a corrupt .hdf, it substitues with nodata:
![image](https://user-images.githubusercontent.com/19994913/101097584-b796b680-35c1-11eb-84a3-1145f359cd05.png)

Default behaviour should be to break when hitting a file that cannot be read

**Comment by interob** [comment]
Example of available metadata for validation:

![image](https://user-images.githubusercontent.com/19994913/101098555-68518580-35c3-11eb-86c6-9bf28c9d9dc0.png)

**Comment by interob** [comment]
I downloaded the file manually: https://e4ftl01.cr.usgs.gov/MOLA/MYD13A2.006/2006.08.21/MYD13A2.A2006233.h19v09.006.2015161155053.hdf

It is perfectly readable.

**Comment by valpesendorfer** [comment]
fixed with #151
