### ISSUE TITLE
MOD13C1 global product is not in EPSG:4326

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#143]
This has popped up in some other project also, see: https://github.com/lucadelu/pyModis/issues/76

`gdalinfo HDF4_EOS:EOS_GRID:"MYD13C1.A2020329.006.2020347091458.hdf":MODIS_Grid_16Day_VI_CMG:"CMG 0.05 Deg 16 days NDVI"` yields:

`GEOGCRS["Unknown datum based upon the Clarke 1866 ellipsoid",
    DATUM["Not specified (based on Clarke 1866 spheroid)",
        ELLIPSOID["Clarke 1866",6378206.4,294.978698213898,
            LENGTHUNIT["metre",1],
            ID["EPSG",7008]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433,
            ID["EPSG",9122]]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]`

Currently, MODAPE is hardcoded to attribute the global product the EPSG:4326 projection, but should be the above SRS definition (does not seem to have an EPSG identifier), or retrieved from downloaded hdf, for example using PyGDAL's `.GetSpatialRef()`.

**Comment by interob** [comment]
With #146, modis/window.py now has a code path to also warp the global product, but is ModisMosaic::_mosaic aware of the non-EPSG projection (see WKT in original post for this issue)?

**Comment by valpesendorfer** [comment]
Yes, if you supply `None` as target projection, it'll default back to the source projection

**Comment by interob** [comment]
I see, nice. I did not dig into the code for this detail, but I think you are saying the during the collect phase, the WKT is taken from the downloaded .hdf and stored as metadata in the .h5 archive, right?

**Comment by valpesendorfer** [comment]
indeed it is

**Comment by valpesendorfer** [comment]
Addressed with #146
