### ISSUE TITLE
Make multithreaded warping optional in modape/window.py

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#144]
See:
https://github.com/WFP-VAM/modape/blob/5dd5fa7b942b0a6f6a946b353050d50b9abda9b2/modape/modis/window.py#L375

Multithreaded processing cannot be trusted 100%, unfortunately. I would like to have this single-threaded by default; multi would be optional. Also: number of threads cannot be specified; that's plain lousy anyway.

**Comment by valpesendorfer** [comment]
implemented with #144
