### ISSUE TITLE
NASA has moved from publishing CKSUM to MD5 hash -- "robust" option for modis_download.py fails

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#172]
Previously, metadata for HDF resources were published as follows:
![image](https://user-images.githubusercontent.com/19994913/188167160-930a79b9-42a0-4913-b49a-b991e60745a3.png)

Which has now become, but only for data that was produced recently:
![image](https://user-images.githubusercontent.com/19994913/188167487-62135cc3-2402-48ec-a7c9-e1e13e814290.png)

MODAPE is hard coded to:
1. parse the published "Checksum" as integer
2. compute the CKSUM hash (integer) on the download and compare

The ChecksumType metadata is not considered.

**Comment by valpesendorfer** [comment]
fixed with #173
