### ISSUE TITLE
Deprecation message in modis_window checks for the wrong argument

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#76]
Looks like the if statement here...

https://github.com/WFP-VAM/modape/blob/72b2d51e3660649cda5dee231d5dfcb606d77084/modape/scripts/modis_download.py#L62

... should check for args.aria2 rather than args.download; "download" remains valid option.

**Comment by valpesendorfer** [comment]
Maybe the message could be a bit clearer. But the idea is that `aria2` will become the default (and only) option - so there's no need for the `--aria2` flag. And the option to actually download data (using aria2) will still be `--download`.
 For now, the `--aria2` flag doesn't do anything, but if it's removed in future releases, it will raise an error.

**Comment by interob** [comment]
I see. But then I would expect the code to check `args.download and not args.aria2`, because I now get the deprecation warning even though I perfectly align with the forced use of aria2.

**Comment by valpesendorfer** [comment]
Well, the code is checking `args.download`.

I see your point though, the deprecation warning is issued even when the `--aria2` flag is not set. Originally I wanted to make sure every user understands that downloading is only possible with `aria2` and adding the flag is redundant (and will cause an error in the future).

Anyways, the correct way is to only issue a warning when the flag is set, I'll change that. Thanks!
