### ISSUE TITLE
Require optv or optvp for initial run of modis_smooth

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#80]
Using modape in the scenario of (a) initial setup and (b) incremental updating (download, collect), without ever explicitly specifying an optimisation method, gives strange results. That is: when updating the dataset, NDVI values seem to receive a negative shift, resulting in smaller and negative values than expected.

Maybe users could be warned when the s grid is not initialised AND no fixed s (or p?) value is provided (because modis_smooth then does try to go with the s grid -- which is not initialised).

**Comment by valpesendorfer** [comment]
Goog point.

I can imagine that it be good to have either 

- a) a check with fail if the user requests an sgrid without having it previously computed.

or
 
- b) a warning for the above.

Currently favoring the check / fail, warnings seem to be ignored frequently.

**Comment by interob** [comment]
I would definitely opt for check / fail
