### ISSUE TITLE
MOD17A2HGF missing

### ISSUE THREAD

**Issue by e5k** [WFP-VAM/modape#86]
Thought I'd mention it here, but cannot use `MOD17A2HGF`, results in `Product MOD17A2HGF not recognized!`

Cheers

**Comment by valpesendorfer** [comment]
Unfortunately the automatic processing chain in `modape` is limited to `M[O,Y]D[11,13]` products. If you have a reasonably small area and just want filtering, you could try `rts_smooth`.

**Comment by e5k** [comment]
Ok thanks. I was just asking as I did not have problems with `MOD17A2H` products

**Comment by valpesendorfer** [comment]
That's curious ... which step in the chain is it? `modis_collect`? Are you using the `cli` tools?

**Comment by e5k** [comment]
Haven't gone past the `modis_download` step yet. Not sure what the `cli` tools is. I can keep you updated.

**Comment by valpesendorfer** [comment]
Ah ok ... well, the products available for download are limited by what was available in the collection 6 product table at that moment (you can print it using `modis_product_table`). It seems like `MOD17A2HGF` is not in there, which throws the error.

With `cli` I meant command line tools, which `modis_download` is one of them. All the tools (and the whole processing chain) was designed for the MODIS NDVI / LST products which means they will unfortunately  not work with the products you are using.

**Comment by valpesendorfer** [comment]
@e5k There's going to be a V1 release of modape, which includes a re-worked querying and downloading module. The querying is now based on MODIS CMR, which enables downloading of all products available through there (which includes MOD17A2HGF).

Please note, the next processing steps will be still limited to `M{O|Y}D{11|13} ` products.
