### ISSUE TITLE
Request: Add optional parameters for rounding and capping

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#88]
Request: introduce parameters for rounding and capping upon grid export (modis/window.py), Explained in more detail below:

**Rounding**: as the value array is retrieved from HDF(s) here...
https://github.com/WFP-VAM/modape/blob/74e380591ef9c8ff68470820fa6943f048275fe2/modape/modis/window.py#L224
... next it would be to round values to an exponent of 10 (e.g. 2 => 10^2 = 100; rounding 10466 would become 10500)

**Capping**: all values in the retrieved array that are below or above the provided minimum or maximum respectively are set to nodata

**Comment by interob** [comment]
Remark: let's stay away from scaling by applying some factor (1/10000 typically) as this would require a change of output datatype

**Comment by valpesendorfer** [comment]
implemented with #104
