### ISSUE TITLE
Request: optional internal tiling in exported tiff

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#89]
creationOptions being set here ...
https://github.com/WFP-VAM/modape/blob/090527c83e9be7a537f761036695b6879659b0be/modape/scripts/modis_window.py#L260
... optionally have tile size set. For example: tile_size = 265 => `['COMPRESS=LZW', 'PREDICTOR=2', 'TILED=YES', 'BLOCKXSIZE=256', 'BLOCKYSIZE=256']`

**Comment by valpesendorfer** [comment]
implemented with #104
