### ISSUE TITLE
modis_collect clean up ingested .hdf files

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#91]
As modis_collect has successfully ingested a .hdf files, optionally have this CLI tool clean up the downloaded file. This feature will play nice with an optional requirement for modis_download for the targeted folder to be empty

It would be best if modis_collect leaves a trace of the delete file, e.g. an (empty) .ingested file with otherwise the same name

**Comment by interob** [comment]
Maybe a ".collected" file, left as a trace for clean up .hdf files, better matches the modape terminology

**Comment by valpesendorfer** [comment]
implemented with #98
